/*
 * This source file was generated by the Gradle 'init' task
 */
package com.royco.jlox;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void appHasAGreeting() {
        Lox classUnderTest = new Lox();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
